qlib_init:
  provider_uri: data/qlib_cn
  region: cn
task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      learning_rate: 0.05
      num_leaves: 127
      max_depth: 8
      subsample: 0.8
      colsample_bytree: 0.9
      num_boost_round: 200
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs:
          start_time: '2024-01-02'
          end_time: '2024-12-31'
          fit_start_time: '2024-01-02'
          fit_end_time: '2024-10-23'
          instruments:
            market: maina
            filter_pipe: []
      segments:
        train:
        - '2024-01-02'
        - '2024-08-07'
        valid:
        - '2024-08-08'
        - '2024-10-23'
        test:
        - '2024-10-24'
        - '2024-12-31'
