qlib_init:
  provider_uri: "data/qlib_cn"
  region: cn

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      learning_rate: 0.05
      num_leaves: 127
      max_depth: 8
      subsample: 0.8
      colsample_bytree: 0.9
      num_boost_round: 200

  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs:
          start_time: "2020-01-01"
          end_time: "2025-12-31"
          fit_start_time: "2020-01-01"
          fit_end_time: "2023-12-31"
          instruments: "all"
      segments:
        train: ["2020-01-01", "2023-12-31"]
        valid: ["2024-01-01", "2024-12-31"]
        test:  ["2025-01-01", "2025-12-31"]
